// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuB1VjxlJd05_F4V2OEH42nx8SUujpHRo',
    appId: '1:539741594088:android:b7d493238d6ab1d6fe445d',
    messagingSenderId: '539741594088',
    projectId: 'booklist-d4ece',
    databaseURL: 'https://booklist-d4ece-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'booklist-d4ece.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO_wsUHw_vbbAmSlKjSetxGWuDL-X-mvE',
    appId: '1:539741594088:ios:f8f20943f6b4bf54fe445d',
    messagingSenderId: '539741594088',
    projectId: 'booklist-d4ece',
    databaseURL: 'https://booklist-d4ece-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'booklist-d4ece.appspot.com',
    iosClientId: '539741594088-i50pami1apikadm0vpmehoa6rbhtr86m.apps.googleusercontent.com',
    iosBundleId: 'com.example.sample',
  );
}
